baseurl = "https://sujaynarumanchi.github.io"
title = "Sujay Narumanchi"
copyright = "&copy; 2016 Sujay Narumanchi"
languageCode = "en-us"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""


[params]
  name = "Sujay Narumanchi"
  role = "Data Scientist"
  organization = "Deep Vision Group at Flipkart"
  avatar = "sujay_profile.jpg"
  email = "sujaynarumanchi@gmail.com"
  # address = "Stanford AI Lab, Stanford University, California, 90210, USA."
  phone = "+91 9980787339"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:sujaynarumanchi@gmail.com"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/SujayNarumanchi"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/sujay-narumanchi-227188b4"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/sujaynarumanchi"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 2


# [[menu.main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 3

[[menu.main]]
  name = "Patents & Publications"
  url = "#patents_publications"
  weight = 4

[[menu.main]]
  name = "Teaching & Talks"
  url = "#talks_teaching"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6
